### ISSUE TITLE
The request query value may be null

### ISSUE THREAD

**Issue by Mkabaka** [esastack/esa-httpclient#99]
### Expected behavior
The `null` value should be allowed as parameter of `HttpRequest#addParam(name, value)`.

### Actual behavior
Unfortunately, the `null` values are not allowed.

### Env
- HttpClient version: v0.1.0

**Comment by LCDZhao-Z** [comment]
Users can use an empty string or string "null" to set the parameter value to "" or "null", which is more explicit.
